server:
  port: 8084

spring:
  application:
    name: api-gateway

  main:
    allow-bean-definition-overriding: true
    web-application-type: reactive

  cloud:
    gateway:
      httpclient:
        connect-timeout: 5000  # Bağlantı kurulamazsa 5 saniyede timeout
        response-timeout: 30s  # order-service içindeki retry'ların tamamlanabilmesi için yeterli timeout

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/api/orders/**
          # Gateway seviyesinde retry ve circuit breaker kaldırıldı
          # çünkü service katmanında Resilience4j ile bu yönetiliyor

        - id: payment-service
          uri: lb://payment-service
          predicates:
            - Path=/api/payments/**

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
